services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_gateway
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "vinay2122@"
      POSTGRES_DB: payment_gateway
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_gateway
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gateway_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_gateway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "vinay2122@"
      SPRING_REDIS_HOST: redis
      REDIS_URL: redis://redis:6379
      TEST_MODE: "true"
      WEBHOOK_RETRY_INTERVALS_TEST: "true"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # worker:  # Workers run inside API container, no separate service needed
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.worker
  #   container_name: gateway_worker
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_gateway
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: "vinay2122@"
  #     SPRING_REDIS_HOST: redis
  #     REDIS_URL: redis://redis:6379
  #     TEST_MODE: "true"
  #     WEBHOOK_RETRY_INTERVALS_TEST: "true"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     api:
  #       condition: service_started

  checkout:
    build:
      context: ./checkout-widget
    container_name: gateway_checkout
    command: ["npm", "run", "serve"]
    ports:
      - "3001:3001"
    depends_on:
      - api

  dashboard:
    build:
      context: ./dashboard
    container_name: gateway_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api

  test-merchant:
    build:
      context: ./test-merchant
    container_name: gateway_test_merchant
    ports:
      - "4000:4000"
    depends_on:
      - api
